sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  # download Snowflake drivers
  - >-
    docker
    run
    -e AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY
    -v `pwd`:/code
    quay.io/keboola/aws-cli
    s3 cp s3://keboola-configs/drivers/snowflake/snowflake-odbc-2.16.6.x86_64.deb /code/snowflake-odbc.deb
  - docker-compose build
script:
  - docker-compose run --rm app ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - docker-compose run --rm app ./vendor/bin/phpunit  --debug --colors=always
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
