version: '2'
services:
  app:
    build: .
    image: keboola/ex-snowflake-query-history
    tty: true
    stdin_open: true
    command: bash
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
  dev:
    image: keboola/ex-snowflake-query-history
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/code
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE

  drivers-download:
    build:
      context: .
      dockerfile: Dockerfile-DriversDownload
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_S3_BUCKET
      - AWS_REGION