version: '2'
services:
  app:
    build: .
    image: keboola/ex-snowflake-query-history
    tty: true
    stdin_open: true
    command: bash
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
  dev:
    image: keboola/ex-snowflake-query-history
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/code
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE