services:
  app: &base
    platform: linux/amd64
    build:
      context: .
    image: keboola/ex-snowflake-query-history
    tty: true
    stdin_open: true
    environment:
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_KEYPAIR
      - SNOWFLAKE_WAREHOUSE
      - KBC_DATADIR=/data

  dev:
    <<: *base
    command: bash
    volumes:
      - ./:/code
      - ./data/:/data
